# 这些是受支持的资金模式平台

GitHub: # 替换为最多 4 个启用了 GitHub Sponsors 的用户名，例如 [user1, user2]: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
Patreon：# 替换为单个 Patreon 用户名: # Replace with a single Patreon username
open_collective: # 替换为单个 Open Collective 用户名: # Replace with a single Open Collective username
ko_fi: # 替换为单个 Ko-fi 用户名: # Replace with a single Ko-fi username
tidelift：# 替换为单个 Tidelift 平台名称/包名称，例如 npm/babel: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # 替换为单个社区桥项目名称，例如 cloud-foundry: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay：# 替换为单个 Liberapay 用户名: # Replace with a single Liberapay username
issuehunt: # 替换为单个 IssueHunt 用户名: # Replace with a single IssueHunt username
lfx_crowdfunding: # 替换为单个 LFX 众筹项目名称，例如 cloud-foundry: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
极地：# 替换为单个极地用户名: # Replace with a single Polar username
buy_me_a_coffee: # 替换为单个 Buy Me a Coffee 用户名: # Replace with a single Buy Me a Coffee username
thanks_dev: # 替换为单个 thanks.dev 用户名: # Replace with a single thanks.dev username
自定义：# 替换为最多 4 个自定义赞助链接，例如 ['链接1', '链接2']: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
